[functions.github-oauth-callback]
verify_jwt = false

[auth]
additional_redirect_urls = ["http://127.0.0.1:5173/**", "http://localhost:5173/**", "https://adarshray.github.io/FamilyTree/**", "familytree://auth/callback", "http://127.0.0.1:5187/auth/callback"]
site_url = "https://adarshray.github.io/FamilyTree/"

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.external.google]
client_id = "370753441716-mvfncs26oh3l84k89ssp66kutkhk4i8c.apps.googleusercontent.com"
enabled = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[storage.vector]
enabled = false
