-- The canonical database schema is maintained as ordered migrations.
-- Start with:
--   supabase/migrations/20260926075607_initial_family_tree_backend.sql
--
-- Apply and validate it with the Supabase CLI rather than running this file.
